apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tfh4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tfh4
    app.kubernetes.io/part-of: integ-app-vnrg
  name: hacbs-test-project-tfh4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tfh4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tfh4
    spec:
      containers:
      - image: quay.io/bootstrap/nbe-e2e-teje-tenant/integ-app-vnrg/hacbs-test-project-tfh4@sha256:76e5fbb928099bd327f2516b1f02f9f94faadc91f19bb84f91e8f6e9a3a66d13
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
