apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tfh4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/bootstrap/nbe-e2e-teje-tenant/integ-app-vnrg/hacbs-test-project-tfh4@sha256:76e5fbb928099bd327f2516b1f02f9f94faadc91f19bb84f91e8f6e9a3a66d13
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
